### PR TITLE
Fixing two issues

### PR DESCRIPTION
**Pull request by azirer**
Related issue 1: https://github.com/optimalisatie/above-the-fold-optimization/issues/30
Related issue 1: https://github.com/optimalisatie/above-the-fold-optimization/issues/24

### CODE REVIEW

**Comment by optimalisatie** [comment]
Hi @azirer,

Thanks a lot for providing the fix! The change of permissions has been applied in `v2.7.12`.

Regarding the use of `rel="abtf"`. It is used as marker for plugins that extract inline CSS from the HTML such as Autoptimize. There is no indication that it breaks [HTML5 validation](https://validator.w3.org/). 

```php
/**
 * Skip CSS from Autoptimize minificaiton
 */
public function skip_css($excludeCSS) {
	$excludeCSS .= ',rel="abtf"';
	return $excludeCSS;
}
```

Do you have more information regarding the breaking of validation?

**Comment by azirer** [comment]
Hi @optimalisatie you should use https://validator.nu for html5 specifically validation. 

See at https://html.spec.whatwg.org/multipage/scripting.html#the-script-element the global attributes that a script element can have.

However I get your point and I would suggest the use of custom data attributes https://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-%2a-attributes. Although I haven't tested them inside scrpt elements I'm pretty sure it will validate. Going to check tomorrow for sure as I'm on mobile right now

**Comment by azirer** [comment]
Just tested data-rel="abtf" instead of rel="abtf" and it validates. 

Be sure to read this ttps://rocketvalidator.com/articles/w3c-validator-is-legacy-long-live-validator-nu and perhaps forget all about validator.w3.org

**Comment by optimalisatie** [comment]
Hi @azirer,

Thanks again for the suggestions and research! The change of the attribute has been applied in `v2.8.0`.

**Pull request closed without merging**
