### PR TITLE
Make it look like a development repo

### PR DESCRIPTION
**Pull request by szepeviktor**
Remove package manager files and make trunk the root.
Plus remove execution bits!

### CODE REVIEW

**Comment by szepeviktor** [comment]
Now it looks like a development repo: https://github.com/szepeviktor/above-the-fold-optimization/tree/reorganize

**Comment by szepeviktor** [comment]
We could add some instruction to the readme on how to build the repo: bower, npm.

**Comment by optimalisatie** [comment]
Hi szepeviktor,

Thanks a lot for your suggestion! This plugin has received less attention from us due to the development of a new plugin.

We have modified the repo according to your request.

**Comment by szepeviktor** [comment]
All right.
You're welcome.

Where is the new plugin?

**Pull request closed without merging**
